### ISSUE TITLE
Communication [pulse sensor firmware] <---> [Rythmus]

### ISSUE THREAD

**Issue by Gouayave** [chevalvert/rythmus#4]
Salut,

Je suis en train d'essayer de comprendre le code, mais je ne vois pas comment le ProMicro communique au reste du système la pulsation récupérée (dans rythmus-sensor/rythmus-sensor.ino).

Est ce qu'il y a un autre MCU qui communique avec le serveur ? Comme dans la trame suivante?
[Pulse sensor] <-1Wire-> [ProMicro] <-??-> [ESP12 devKit] <-Ethernet/wifi-> [PC Server]

Merci pour ta/votre réponse.
Belle journée.

**Comment by arnaudjuracek** [comment]
Le ProMicro envoie les données brutes via serial, et après y'a un système d'abstractions côté node qui se charge de parser puis analyser le signal : 


[ProMicro](https://github.com/chevalvert/rythmus-sensor/blob/master/rythmus-sensor.ino#L39-L41) → [`abstractions/Sensor`](https://github.com/chevalvert/rythmus/blob/master/lib/abstractions/Sensor.js#L67-L68) → [`abstractions/Heart`](https://github.com/chevalvert/rythmus/blob/master/lib/abstractions/Heart.js) + [`abstractions/PulseSample`](https://github.com/chevalvert/rythmus/blob/master/lib/abstractions/)

Théoriquement la lib de pulseSensor côté ProMicro pourrait sortir les valeurs de BPM etc, mais pour tout un tas de raisons j'ai préféré réimplémenter côté node toute l'abstractions de calcul de pouls à partir de la valeur brute du signal.

L'architecture côté node c'est donc :
- une abstraction [`Sensor`](https://github.com/chevalvert/rythmus/blob/master/lib/abstractions/Sensor.js) qui se charge de gérer le protocole de communication, ouverture fermeture serial, mocking possible pour le dev etc.
- une abstraction [`Heart`](https://github.com/chevalvert/rythmus/blob/master/lib/abstractions/Heart.js) qui étend le capteur et produit une API qui permet de savoir si un cœur capté est en train de battre, à quel rythme (BPM), produit un event emitter lorsqu'un battement apparaît, etc.
- une abstraction [`PulseSample`](https://github.com/chevalvert/rythmus/blob/master/lib/abstractions/) à l'intérieur de l'abstraction [`Heart`](https://github.com/chevalvert/rythmus/blob/master/lib/abstractions/Heart.js) qui se charge d'échantilloner le signal pour faire une passe de filtre etc.
- une abstraction [`Player`](https://github.com/chevalvert/rythmus/blob/master/lib/abstractions/Player.js) qui contient un [`Heart`](https://github.com/chevalvert/rythmus/blob/master/lib/abstractions/Heart.js), mais aussi des informations liées à sa couleur, à l'animation et au son qu'il provoque, mais surtout à sa présence (si le joueur est bien actif et a son doigt posé sur le capteur).

**Comment by Gouayave** [comment]
Merci pour cette réponse rapide.
Ok j'avais plus cette notion d’abstraction. Parfait.

Et deux autres questions du coup:
- Est ce qu'il y a un "technicien" en permanence sur le pc serveur (nodejs), qui choisi les paysages? ou "le technicien" instancie le système avant la représentation? Du coup, le pc serveur c'est un "raspberry" qui est dans une boite étanche ou c'est un portable (avec technicien) dans un camion à coté ?

- Tu as le modèle du capacitive sensor ? 

Merci encore ! C'est vraiment sympa !

**Comment by arnaudjuracek** [comment]
Il n'y a pas de notion de "live" sur Rythmus si c'est ta question, tout est défini à l'avance ([`animations/`](https://github.com/chevalvert/rythmus/tree/master/lib/animations)), et à chaque présence détectée d'un utilisateur (pose du doigt sur la capacitif), une nouvelle animation est tiré au sort. 
Les animations de base peuvent proposer des variations ([`index.js#L11-L24`](https://github.com/chevalvert/rythmus/blob/master/index.js#L11-L24)) qui correspondent simplement à des configurations différentes ([`config.fdl.json`](https://github.com/chevalvert/rythmus/blob/master/config/config.fdl.json#L9-L88)).

Côté hardware, le serveur est un mac mini dans une boîte étanche, configuré pour se lancer automatiquement lorsque l'installation démarre (on utilise un mac mini parce que la partie son est géré par Ableton Live).

Pour le capacitive sensor, il s'agit simplement de ruban adhésive en aluminium, du type de ceux utilisés en plomberie : [Native Capacitive Sensors without additional Hardware](https://playground.arduino.cc/Code/CapacitiveSensor/).

**Comment by Gouayave** [comment]
Ok.  J'ai tout. Tu gères !
